apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not ( .Values.adminTokenExistingSecret ) }}
  ADMIN_TOKEN: {{ .Values.adminToken | b64enc | quote }}
  {{- end }}
  {{- if not ( .Values.smtp.existingSecret ) }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if not ( .Values.pushNotifications.existingSecret ) }}
  PUSH_INSTALLATION_ID: {{ .Values.pushNotifications.installationId | b64enc | quote }}
  PUSH_INSTALLATION_KEY: {{ .Values.pushNotifications.installationKey | b64enc | quote }}
  {{- end }}
