apiVersion: v2
name: adguard-home
description: A Helm chart for AdGuard Home
type: application
version: 0.0.5
appVersion: "v0.107.64"
keywords:
  - adguard
  - adblocker
  - dns
home: https://github.com/Jubast/homeserver-helm-charts/tree/main/charts/adguard-home
maintainers:
  - name: Jubast
    email: 30406814+Jubast@users.noreply.github.com
    url: https://github.com/Jubast
dependencies:
  - name: common
    repository: https://jubast.github.io/homeserver-helm-charts/
    version: 1.0.0
